name: Auto PR to staging2

on:
  push:
    branches:
      - master

jobs:
  create-pr:
    uses: ./.github/workflows/create-pr.yml
    with:
      base_branch: staging2
      head_branch: master
      pr_title: "Auto PR: Update staging2 from master"
      pr_body: "This PR was automatically created when master branch was updated."

